# Generated by Django 6.0.6 on 2026-07-04 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('national_id', models.CharField(blank=True, help_text='National ID / Aadhar / Passport', max_length=50)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('insurance_number', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('waiting', 'Waiting for Doctor'), ('in_consultation', 'In Consultation'), ('lab_requested', 'Lab Test Requested'), ('lab_in_progress', 'Lab Test In Progress'), ('lab_completed', 'Lab Results Ready'), ('imaging_requested', 'Imaging Requested'), ('imaging_completed', 'Imaging Completed'), ('treated', 'Treated'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='registered', max_length=20)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('lab_test_requested', models.TextField(blank=True)),
                ('lab_test_results', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imaging_requested', models.TextField(blank=True, help_text='Imaging tests requested by doctor')),
                ('imaging_results', models.TextField(blank=True, help_text='Results from imaging')),
                ('assigned_doctor', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='staff.staffprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospitals.hospital')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('hospital', 'mrn')},
            },
        ),
    ]
