# Generated by Django 6.0.6 on 2026-07-08 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_trusteddevice_risk_metadata'),
        ('patients', '0001_initial'),
        ('rooms', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('release_reason', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_assignments_created', to='staff.staffprofile')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rooms.bed')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_assignments', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_assignments', to='patients.patient')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_assignments_released', to='staff.staffprofile')),
                ('transfer_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_children', to='rooms.bedassignment')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('bed',), name='uniq_active_assignment_per_bed'), models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('patient',), name='uniq_active_assignment_per_patient')],
            },
        ),
    ]
