# Generated by Django 6.0.6 on 2026-07-09 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_subscriptionpayment_idempotency_key'),
        ('hospitals', '0006_trusteddevice_risk_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Lab'), ('other', 'Other Service')], default='other', max_length=20)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_catalog', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['service_type', 'name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
    ]
