# Generated by Django 6.0.6 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_posreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='imaging_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='service_type',
            field=models.CharField(
                choices=[
                    ('consultation', 'Consultation'),
                    ('lab', 'Lab'),
                    ('imaging', 'Imaging'),
                    ('other', 'Other Service'),
                ],
                default='other',
                max_length=20,
            ),
        ),
    ]