# Generated by Django 6.0.6 on 2026-07-15 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_hospital_domain_last_resolved_ip_and_more'),
        ('saas_billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('trial_7_days', 'Trial Ends in 7 Days'), ('trial_3_days', 'Trial Ends in 3 Days'), ('trial_today', 'Trial Ends Today'), ('invoice_7_days', 'Invoice Due in 7 Days'), ('invoice_3_days', 'Invoice Due in 3 Days'), ('invoice_today', 'Invoice Due Today'), ('overdue_3_days', 'Invoice Overdue by 3 Days'), ('overdue_7_days', 'Invoice Overdue by 7 Days')], db_index=True, max_length=40)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_date', models.DateField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_reminder_logs', to='hospitals.hospital')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='saas_billing.invoice')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='saas_billing.hospitalsubscription')),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('hospital', 'invoice', 'reminder_type', 'billing_date'), name='unique_invoice_reminder_per_date'), models.UniqueConstraint(fields=('hospital', 'subscription', 'reminder_type', 'billing_date'), name='unique_subscription_reminder_per_date')],
            },
        ),
    ]
