# Generated by Django 6.0.6 on 2026-07-15 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0003_hospitalbillingnote_hospitalcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsubscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_hospital_subscriptions', to='saas_billing.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='hospitalsubscription',
            name='pending_plan_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalsubscription',
            name='pending_plan_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
