# Generated by Django 6.0.6 on 2026-07-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0004_hospitalsubscription_pending_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_delivery_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_sent', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
