# Generated by Django 6.0.6 on 2026-08-10 16:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import saas_billing.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_subscription_cycles(apps, schema_editor):
    SubscriptionPlan = apps.get_model('saas_billing', 'SubscriptionPlan')
    HospitalSubscription = apps.get_model(
        'saas_billing',
        'HospitalSubscription',
    )
    Payment = apps.get_model('saas_billing', 'Payment')

    for plan in SubscriptionPlan.objects.all().iterator():
        plan.six_month_price = plan.monthly_price * 6
        plan.annual_price = plan.monthly_price * 12
        plan.save(update_fields=['six_month_price', 'annual_price'])

    for subscription in HospitalSubscription.objects.all().iterator():
        subscription.start_date = subscription.started_at.date()
        subscription.end_date = subscription.next_billing_date
        subscription.save(update_fields=['start_date', 'end_date'])

    for payment in Payment.objects.select_related('subscription').iterator():
        payment.plan_id = payment.subscription.plan_id
        payment.billing_cycle = payment.subscription.billing_cycle
        payment.save(update_fields=['plan', 'billing_cycle'])


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0009_separate_starter_trial_from_basic_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('six_months', 'Six Months'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='hospitalsubscription',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalsubscription',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalsubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('six_months', 'Six Months'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_saas_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='saas_billing.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to=saas_billing.models.payment_proof_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg']), saas_billing.models.validate_payment_proof_size]),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_saas_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='six_month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='hospitalsubscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('grace', 'Grace Period'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='trial', max_length=20),
        ),
        migrations.RunPython(
            backfill_subscription_cycles,
            migrations.RunPython.noop,
        ),
    ]
