# Generated by Django 6.0.6 on 2026-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('hospital_type', models.CharField(choices=[('general', 'General Hospital'), ('specialty', 'Specialty Hospital'), ('clinic', 'Clinic'), ('diagnostic', 'Diagnostic Center')], max_length=20)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='South Sudan', max_length=100)),
                ('subscription_plan', models.CharField(choices=[('trial', '14-Day Free Trial'), ('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('subscription_status', models.CharField(default='active', max_length=20)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('max_staff', models.IntegerField(default=5)),
                ('max_patients', models.IntegerField(default=500)),
                ('logo', models.ImageField(blank=True, upload_to='hospital_logos/')),
                ('timezone', models.CharField(default='Africa/Juba', max_length=50)),
                ('currency', models.CharField(default='SSP', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
