# Generated by Django 6.0.6 on 2026-07-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hospital',
            name='primary_color',
            field=models.CharField(default='#F97316', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='secondary_color',
            field=models.CharField(default='#1E3A5F', max_length=20),
        ),
    ]
