# Generated by Django 6.0.6 on 2026-07-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_trusteddevice_risk_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='domain_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='domain_status',
            field=models.CharField(choices=[('unconfigured', 'Unconfigured'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Failed Verification')], default='unconfigured', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='domain_verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hospital',
            name='domain_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
