# Generated by Django 6.0.6 on 2026-07-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_hospital_domain_last_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='domain_last_resolved_ip',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hospital',
            name='domain_ssl_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='domain_ssl_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
