# Generated by Django 6.0.6 on 2026-07-22 10:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('allocated_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('carried_forward_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('adjustment_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='human_resources.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_balances', to='human_resources.leavetype')),
            ],
            options={
                'ordering': ['-year', 'employee__first_name', 'leave_type__name'],
                'indexes': [models.Index(fields=['year', 'is_active'], name='human_resou_year_bbfce0_idx'), models.Index(fields=['employee', 'year'], name='human_resou_employe_d7131f_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_employee_leave_balance_per_year')],
            },
        ),
    ]
