# Generated by Django 6.0.6 on 2026-07-22 11:58

import human_resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_leavebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(default=human_resources.models._default_leave_year),
        ),
    ]
