# Generated by Django 6.0.6 on 2026-07-27 12:16

import config.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_fix_leave_balance_year_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=config.encrypted_fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=config.encrypted_fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_number',
            field=config.encrypted_fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_number',
            field=config.encrypted_fields.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
