# Generated by Django 6.0.6 on 2026-07-22 20:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0008_hospital_domain_last_resolved_ip_and_more'),
        ('human_resources', '0003_fix_leave_balance_year_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_types', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_types', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_years', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('processed', 'Processed'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='human_resources.employee')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('salary_slip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='finance.salaryslip')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='SalarySlipDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.deductiontype')),
                ('salary_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='finance.salaryslip')),
            ],
            options={
                'ordering': ['deduction_type'],
            },
        ),
        migrations.CreateModel(
            name='SalarySlipEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.allowancetype')),
                ('salary_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='finance.salaryslip')),
            ],
            options={
                'ordering': ['allowance_type'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='salary_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.salarystructure'),
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='human_resources.employee')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.salarystructure')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructureAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_percentage', models.BooleanField(default=False)),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.allowancetype')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='finance.salarystructure')),
            ],
            options={
                'ordering': ['allowance_type'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_percentage', models.BooleanField(default=False)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.deductiontype')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='finance.salarystructure')),
            ],
            options={
                'ordering': ['deduction_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='allowancetype',
            constraint=models.UniqueConstraint(fields=('hospital', 'code'), name='unique_hospital_allowance_code'),
        ),
        migrations.AddConstraint(
            model_name='deductiontype',
            constraint=models.UniqueConstraint(fields=('hospital', 'code'), name='unique_hospital_deduction_code'),
        ),
        migrations.AddConstraint(
            model_name='payrollyear',
            constraint=models.UniqueConstraint(fields=('hospital', 'year'), name='unique_hospital_payroll_year'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='unique_hospital_salary_structure'),
        ),
        migrations.AddConstraint(
            model_name='salaryslip',
            constraint=models.UniqueConstraint(fields=('employee', 'month'), name='unique_employee_salary_slip'),
        ),
        migrations.AddConstraint(
            model_name='employeesalary',
            constraint=models.UniqueConstraint(fields=('employee', 'salary_structure'), name='unique_employee_salary_structure'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureallowance',
            constraint=models.UniqueConstraint(fields=('salary_structure', 'allowance_type'), name='unique_structure_allowance'),
        ),
        migrations.AddConstraint(
            model_name='salarystructurededuction',
            constraint=models.UniqueConstraint(fields=('salary_structure', 'deduction_type'), name='unique_structure_deduction'),
        ),
    ]
