# Generated by Django 6.0.6 on 2026-08-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_journalentryline_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='salary_slip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='finance.salaryslip'),
        ),
    ]
