# Generated by Django 6.0.6 on 2026-08-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_payrollyear_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('processed', 'Processed'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
