# Generated by Django 6.0.6 on 2026-07-16 08:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0007_posreceipt'),
        ('hospitals', '0008_hospital_domain_last_resolved_ip_and_more'),
        ('patients', '0001_initial'),
        ('pharmacy', '0002_prescription_medicine_amount'),
        ('rooms', '0002_bedassignment'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('admission_type', models.CharField(choices=[('emergency', 'Emergency'), ('elective', 'Elective'), ('transfer', 'Transfer'), ('observation', 'Observation')], default='elective', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('transferred', 'Transferred'), ('discharged', 'Discharged'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('provisional_diagnosis', models.TextField()),
                ('reason_for_admission', models.TextField()),
                ('presenting_complaint', models.TextField(blank=True)),
                ('admission_notes', models.TextField(blank=True)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ipd_admissions', to=settings.AUTH_USER_MODEL)),
                ('admitting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions_as_doctor', to='staff.staffprofile')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions', to='rooms.bed')),
                ('bed_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions', to='rooms.bedassignment')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions', to='billing.bill')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipd_admissions', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to='patients.patient')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions', to='rooms.room')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions', to='rooms.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_type', models.CharField(choices=[('home', 'Home'), ('transfer', 'Transfer'), ('against_advice', 'Against Medical Advice'), ('deceased', 'Deceased'), ('referred', 'Referred')], default='home', max_length=30)),
                ('final_diagnosis', models.TextField()),
                ('clinical_summary', models.TextField()),
                ('treatment_summary', models.TextField(blank=True)),
                ('condition_at_discharge', models.TextField(blank=True)),
                ('discharge_medications', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('discharged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summary', to='ipd.admission')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ipd_discharges', to=settings.AUTH_USER_MODEL)),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_discharges', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-discharged_at'],
            },
        ),
        migrations.CreateModel(
            name='InpatientMedicationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_orders', to='ipd.admission')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_medication_orders', to='pharmacy.medicine')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_medication_orders', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InpatientTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='ipd.admission')),
                ('from_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_transfers_from', to='rooms.bed')),
                ('from_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_transfers_from', to='rooms.room')),
                ('from_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_transfers_from', to='rooms.ward')),
                ('to_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_to', to='rooms.bed')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_to', to='rooms.room')),
                ('to_ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_to', to='rooms.ward')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dosage_given', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('was_refused', models.BooleanField(default=False)),
                ('refusal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_medication_administrations', to='staff.staffprofile')),
                ('medication_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='ipd.inpatientmedicationorder')),
            ],
            options={
                'ordering': ['-administered_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fluid_intake_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('fluid_output_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consciousness_level', models.CharField(blank=True, max_length=100)),
                ('nursing_notes', models.TextField(blank=True)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_observations', to='ipd.admission')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_nursing_observations', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['hospital', 'status'], name='ipd_admissi_hospita_a6eaf4_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['hospital', 'patient'], name='ipd_admissi_hospita_e5f9dc_idx'),
        ),
    ]
