# Generated by Django 6.0.6 on 2026-07-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_trusteddevice_risk_metadata'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompany',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='insurancecompany',
            constraint=models.UniqueConstraint(fields=('hospital', 'code'), name='uniq_insurance_company_code_per_hospital'),
        ),
    ]
