# Generated by Django 6.0.6 on 2026-07-27 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insurancecompany_code_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims', to='patients.patient'),
        ),
    ]
