# Generated by Django 6.0.6 on 2026-08-13 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_add_patient_fk_to_insuranceclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaim',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.insurancecompany'),
        ),
    ]
