# Generated by Django 6.0.6 on 2026-08-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensepayment',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='expenses.expense'),
        ),
    ]
