# Generated by Django 6.0.6 on 2026-08-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0004_auditlog_action_detail_auditlog_changes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='notification_type',
            field=models.CharField(choices=[('otp', 'OTP'), ('receipt', 'Receipt'), ('security_alert', 'Security Alert')], max_length=20),
        ),
    ]
