# Generated by Django 6.0.6 on 2026-08-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0005_alter_notificationevent_notification_type'),
        ('hospitals', '0008_hospital_domain_last_resolved_ip_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['hospital', '-created_at'], name='auditlog_au_hospita_b5f6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', '-created_at'], name='auditlog_au_action__1dc49a_idx'),
        ),
    ]
