# Generated by Django 6.0.6 on 2026-07-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiographer', 'Radiographer'), ('accountant', 'Accountant'), ('finance', 'Finance Officer'), ('finance_manager', 'Finance Manager'), ('cashier', 'Cashier'), ('hr', 'HR Officer'), ('hr_officer', 'HR Officer'), ('hr_manager', 'HR Manager')], max_length=20),
        ),
    ]
