from django.urls import path

from .billing_center_views import (
    billing_center_analytics,
    billing_center_approve_payment,
    billing_center_billing_notes,
    billing_center_change_plan,
    billing_center_dashboard,
    billing_center_download_invoice_pdf,
    billing_center_download_receipt_pdf,
    billing_center_end_trial,
    billing_center_extend_trial,
    billing_center_generate_invoice,
    billing_center_hospital_credits,
    billing_center_hospital_detail,
    billing_center_hospitals,
    billing_center_invoices,
    billing_center_invoices_csv,
    billing_center_mark_invoice_overdue,
    billing_center_mark_invoice_paid,
    billing_center_payments,
    billing_center_payments_csv,
    billing_center_reactivate_subscription,
    billing_center_reject_payment,
    billing_center_resend_invoice_reminder,
    billing_center_revenue_csv,
    billing_center_suspend_subscription,
    billing_center_void_invoice,
    billing_center_waive_service_fee,
)


urlpatterns = [
    path(
        "dashboard/",
        billing_center_dashboard,
        name="billing-center-dashboard",
    ),
    path(
        "analytics/",
        billing_center_analytics,
        name="billing-center-analytics",
    ),
    path(
        "reports/revenue.csv",
        billing_center_revenue_csv,
        name="billing-center-revenue-csv",
    ),
    path(
        "reports/invoices.csv",
        billing_center_invoices_csv,
        name="billing-center-invoices-csv",
    ),
    path(
        "reports/payments.csv",
        billing_center_payments_csv,
        name="billing-center-payments-csv",
    ),
    path(
        "invoices/",
        billing_center_invoices,
        name="billing-center-invoices",
    ),
    path(
        "invoices/<int:invoice_id>/void/",
        billing_center_void_invoice,
        name="billing-center-void-invoice",
    ),
    path(
        "invoices/<int:invoice_id>/mark-overdue/",
        billing_center_mark_invoice_overdue,
        name="billing-center-mark-invoice-overdue",
    ),
    path(
        "invoices/<int:invoice_id>/mark-paid/",
        billing_center_mark_invoice_paid,
        name="billing-center-mark-invoice-paid",
    ),
    path(
        "invoices/<int:invoice_id>/pdf/",
        billing_center_download_invoice_pdf,
        name="billing-center-invoice-pdf",
    ),
    path(
        "payments/",
        billing_center_payments,
        name="billing-center-payments",
    ),
    path(
        "payments/<int:payment_id>/approve/",
        billing_center_approve_payment,
        name="billing-center-approve-payment",
    ),
    path(
        "payments/<int:payment_id>/reject/",
        billing_center_reject_payment,
        name="billing-center-reject-payment",
    ),
    path(
        "payments/<int:payment_id>/receipt-pdf/",
        billing_center_download_receipt_pdf,
        name="billing-center-receipt-pdf",
    ),
    path(
        "hospitals/",
        billing_center_hospitals,
        name="billing-center-hospitals",
    ),
    path(
        "hospitals/<int:hospital_id>/",
        billing_center_hospital_detail,
        name="billing-center-hospital-detail",
    ),
    path(
        "hospitals/<int:hospital_id>/extend-trial/",
        billing_center_extend_trial,
        name="billing-center-extend-trial",
    ),
    path(
        "hospitals/<int:hospital_id>/end-trial/",
        billing_center_end_trial,
        name="billing-center-end-trial",
    ),
    path(
        "hospitals/<int:hospital_id>/suspend/",
        billing_center_suspend_subscription,
        name="billing-center-suspend-subscription",
    ),
    path(
        "hospitals/<int:hospital_id>/reactivate/",
        billing_center_reactivate_subscription,
        name="billing-center-reactivate-subscription",
    ),
    path(
        "hospitals/<int:hospital_id>/change-plan/",
        billing_center_change_plan,
        name="billing-center-change-plan",
    ),
    path(
        "hospitals/<int:hospital_id>/waive-service-fee/",
        billing_center_waive_service_fee,
        name="billing-center-waive-service-fee",
    ),
    path(
        "hospitals/<int:hospital_id>/generate-invoice/",
        billing_center_generate_invoice,
        name="billing-center-generate-invoice",
    ),
    path(
        "hospitals/<int:hospital_id>/resend-invoice-reminder/",
        billing_center_resend_invoice_reminder,
        name="billing-center-resend-invoice-reminder",
    ),
    path(
        "hospitals/<int:hospital_id>/notes/",
        billing_center_billing_notes,
        name="billing-center-billing-notes",
    ),
    path(
        "hospitals/<int:hospital_id>/credits/",
        billing_center_hospital_credits,
        name="billing-center-hospital-credits",
    ),
]
