# Generated by Django 6.0.6 on 2026-07-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
